const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$("#menuBtn")?.addEventListener("click",()=>$("#mainNav").classList.toggle("open"));
let state={needs:[],style:"friend"};
$$("[data-need]").forEach(b=>b.addEventListener("click",()=>{b.classList.toggle("selected");state.needs=$$("[data-need].selected").map(x=>x.dataset.need);$("#styleBox").classList.remove("hidden");$("#profileBox").classList.remove("hidden")}));
$$("[data-style]").forEach(b=>b.addEventListener("click",()=>{$$("[data-style]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.style=b.dataset.style}));
function enterChat(){const name=$("#nickname").value.trim()||"human";$("#onboarding").classList.add("hidden");$("#chat").classList.remove("hidden");let mode=state.style==="teacher"?"I’ll keep things clear and explain step by step.":state.style==="listen"?"I’ll give you space. You don't need to fill every silence.":state.style==="calm"?"We can take this slowly, one small step at a time.":"I’ll keep things warm, simple, and human.";$("#messages").innerHTML=`<div class="bubble bird-bubble">Hey, ${esc(name)}. ${mode} What's on your mind?</div>`}
$("#enter").onclick=enterChat;$("#skip").onclick=enterChat;
$("#restart").onclick=()=>{$("#chat").classList.add("hidden");$("#onboarding").classList.remove("hidden");$("#styleBox").classList.add("hidden");$("#profileBox").classList.add("hidden");$$(".choice").forEach(x=>x.classList.remove("selected"))};
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function add(text,who){const d=document.createElement("div");d.className=`bubble ${who==="bird"?"bird-bubble":"user-bubble"}`;d.textContent=text;$("#messages").appendChild(d);$("#messages").scrollTop=$("#messages").scrollHeight}
function response(t){const x=t.toLowerCase();if(/kill myself|suicide|self[- ]harm|hurt myself|end my life/.test(x))return"I'm really glad you said something. I can't help with instructions for hurting yourself. If you may be in immediate danger, please contact local emergency services or a trusted person who can stay with you. If you share your country, a production version of Lil Bird can help identify appropriate crisis support.";if(/medication|medicine|pill|dose/.test(x))return"I can explain general information about treatment, but I can't prescribe or recommend medication or a dose. A qualified clinician or pharmacist can help with that safely.";if(/anxious|anxiety|panic|overwhelmed|stressed/.test(x))return"Okay, let's slow this down. You don't have to solve everything at once. If you want, tell me what is happening right now, or I can explain what psychology says about stress and anxiety.";if(/psychology|neuroscience|brain|memory|emotion|trauma|cognitive/.test(x))return"I can explain that in layers: a simple version, an everyday example, the deeper psychology or neuroscience, and then sources. Which layer do you want first?";if(/don't know|dont know|nothing/.test(x))return"That's okay. You don't need perfect words. We can start with one tiny thing: what feels most noticeable right now?";return"I'm listening. You can tell me as much or as little as you want. If you'd rather learn about what's happening psychologically, I can explain that too."}
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();const i=$("#chatInput"),t=i.value.trim();if(!t)return;add(t,"user");i.value="";setTimeout(()=>add(response(t),"bird"),280)});
$$(".quick button").forEach(b=>b.addEventListener("click",()=>{const t=b.dataset.q;add(t,"user");setTimeout(()=>add(response(t),"bird"),280)}));
$$("[data-chat]").forEach(b=>b.addEventListener("click",()=>{location.hash="#talk";setTimeout(()=>{if($("#chat").classList.contains("hidden"))enterChat();const t=b.dataset.chat;add(t,"user");setTimeout(()=>add(response(t),"bird"),280)},150)}));